marketplace_domains:
  - "alibaba.com"
  - "made-in-china.com"
  - "indiamart.com"
  - "tradeindia.com"
  - "metoree.com"
  - "ipros.com"
  - "echemi.com"
  - "taiwantrade.com"
  - "paperindex.com"
  - "justdial.com"
  - "chemicalbook.com"
  - "pharmacompass.com"
  - "industrystock.com"
  - "volza.com"
  - "zauba.com"
  - "exportgenius.in"
  - "b2brazil.com"
  - "tradeimex.in"
