exclude_domains:
  - "wikipedia.org"
  - "simple.wikipedia.org"
  - "geeksforgeeks.org"
  - "study.com"
  - "byjus.com"
  - "chefsteps.com"
  - "youtube.com"
  - "facebook.com"
  - "instagram.com"
  - "linkedin.com"
  - "scribd.com"
  - "reddit.com"
  - "quora.com"
  - "pmc.ncbi.nlm.nih.gov"
  - "pubchem.ncbi.nlm.nih.gov"
