exclude_domains:
  - "wikipedia.org"
  - "simple.wikipedia.org"
  - "geeksforgeeks.org"
  - "study.com"
  - "byjus.com"
  - "chefsteps.com"
  - "youtube.com"
  - "facebook.com"
  - "instagram.com"
  - "linkedin.com"
  - "scribd.com"
  - "reddit.com"
  - "quora.com"
  - "pmc.ncbi.nlm.nih.gov"
  - "pubchem.ncbi.nlm.nih.gov"
  - "mordorintelligence.com"
  - "persistencemarketresearch.com"
  - "sphericalinsights.com"
  - "verifiedmarketresearch.com"
  - "polarismarketresearch.com"
  - "reportsanddata.com"
  - "marketsandmarkets.com"
  - "marketreportsworld.com"
  - "indexbox.io"
  - "tridge.com"
  - "accio.com"
  - "sourcifychina.com"
  - "databridgemarketresearch.com"
  - "camaphosphoricacid.com"
  - "marketresearchfuture.com"
  - "statista.com"
  - "prnewswire.com"
  - "argusmedia.com"
