base_templates:
  - "{product_name} manufacturer"
  - "{product_name} producer"
  - "{product_name} technical data sheet"
  - "{product_name} supplier"
  - "{product_name} CAS"

category_templates:
  - "{product_name} {category} manufacturer"
  - "{product_name} {category} producer"
  - "{product_name} {category} technical data sheet"
  - "{product_name} {category} supplier"
  - "{product_name} {category} CAS"
